%{!?python_sitelib: %global python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}

%define libname totpcgi

Name:		python-%{libname}
Version:	0.3.1
Release:	2%{?dist}
Summary:	A centralized totp solution based on google-authenticator

License:	GPLv2+
URL:		https://github.com/mricon/totp-cgi
Source0:	%{libname}-%{version}.tar.gz

BuildArch:	noarch

Requires:	py-bcrypt, python-pyotp, google-authenticator
Requires:	httpd, mod_ssl, selinux-policy

%description
The idea of totp-cgi came when lamenting that google-authenticator 
implementation is "almost there" to be used as a generic org-wide 
2-factor solution, but is annoyingly written to be a one-secret-per-service 
(or -per-host) solution. Thus, totp-cgi was born, which uses files 
generated by google-authenticator and serves them from a central installation.

It is intended to be used with pam_url.

%prep
%setup -q -n %{libname}-%{version}


%build
%{__python} setup.py build


#%check
#%{__python} test.py


%install
%{__rm} -rf ${RPM_BUILD_ROOT}
%{__python} setup.py install -O1 --skip-build --root ${RPM_BUILD_ROOT}
%{__mkdir} -p -m 0750 ${RPM_BUILD_ROOT}%{_sysconfdir}/%{libname}/totp
%{__install} -m 0440 %{libname}.conf ${RPM_BUILD_ROOT}%{_sysconfdir}/%{libname}/
%{__mkdir} -p -m 0700 ${RPM_BUILD_ROOT}%{_localstatedir}/lib/%{libname}
%{__mkdir} -p ${RPM_BUILD_ROOT}%{_localstatedir}/www/%{libname}
%{__install} -m 0550 totp.cgi ${RPM_BUILD_ROOT}%{_localstatedir}/www/%{libname}/
%{__mkdir} -p ${RPM_BUILD_ROOT}%{_sysconfdir}/httpd/conf.d
%{__install} -m 0644 contrib/vhost-totp-cgi.conf ${RPM_BUILD_ROOT}%{_sysconfdir}/httpd/conf.d/totp-cgi.conf


%pre
# Add the "totpcgi" user
/usr/sbin/useradd -c "Totp-cgi user" \
	-M -s /sbin/nologin -d /var/lib/%{libname} %{libname} 2> /dev/null || :


%post
# install the selinux policy
cd %{_docdir}/%{name}-%{version}/selinux
./totpcgi.sh


%preun
# only do this on a full removal
if [ $1 = 0 ]; then
	# remove the selinux policy
	/usr/sbin/semodule -r totpcgi
	# Cleanup from our original install of the policy
	# I would use a ghost tag but it's annoying sometimes
	%{__rm} -rf %{_docdir}/%{name}-%{version}/selinux/tmp
	%{__rm} -f %{_docdir}/%{name}-%{version}/selinux/totpcgi.pp
fi


%files
%doc README.rst COPYING INSTALL.rst
%doc selinux contrib/*.conf contrib/*sql
%doc contrib/pincode.py
%doc totp.fcgi
%{python_sitelib}/*
%attr(0750, root, %{libname}) %{_sysconfdir}/%{libname}
%attr(-, %{libname}, %{libname}) %{_localstatedir}/lib/%{libname}
%attr(0551, %{libname}, %{libname}) %{_localstatedir}/www/%{libname}
%attr(0550, %{libname}, %{libname}) %{_localstatedir}/www/%{libname}/totp.cgi
%config %attr(0440, -, %{libname}) %{_sysconfdir}/%{libname}/%{libname}.conf
%config %attr(0644, -, -) %{_sysconfdir}/httpd/conf.d/totp-cgi.conf


%changelog
* Tue May 01 2012 Andrew Grimberg <agrimberg@linuxfoundation.org> - 0.3.1-2
- Exceptions on bad passwords to LDAP
- Config for CA cert to use for verification
- PostgreSQL pincode & secrets backends

* Thu Apr 12 2012 Andrew Grimberg <agrimberg@linuxfoundation.org> - 0.3.0-1
- Bump version number
- Split backend system

* Wed Apr 11 2012 Andrew Grimberg <agrimberg@linuxfoundation.org> - 0.2.0-4
- Add in pincode.py script

* Mon Mar 26 2012 Andrew Grimberg <agrimberg@linuxfoundation.org> - 0.2.0-3
- Fix path perms for /var/www/totpcgi so that apache can chdir
- Reduce perms on /var/www/totpcgi/totp.cgi to bare minimum

* Fri Mar 23 2012 Konstantin Ryabitsev <mricon@kernel.org> - 0.2.0-2
- Update to better match Fedora's spec standards.

* Wed Mar 21 2012 Andrew Grimberg <agrimberg@linuxfoundation.org> - 0.2.0-1
- Initial spec file creation and packaging
