%{!?python_sitelib: %global python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}

%define libname totpcgi

Name:		python-%{libname}
Version:	0.2.0
Release:	1%{?dist}
Summary:	A centralized totp solution based on google-authenticator

License:	GPL
URL:		https://github.com/mricon/totp-cgi
Source0:	%{libname}-%{version}.tar.gz

BuildArch:	noarch

Requires:	py-bcrypt, python-pyotp, google-authenticator
Requires:	httpd, mod_ssl, selinux-policy

%description
The idea of totp-cgi came when lamenting that google-authenticator implementation is "almost there" to be used as a generic org-wide 2-factor solution, but is annoyingly written to be a one-secret-per-service (or -per-host) solution. Thus, totp-cgi was born, which uses files generated by google-authenticator and serves them from a central installation.

It is intended to be used with pam_url.

%prep
%setup -q -n %{libname}-%{version}


%build
%{__python} setup.py build


#%check
#%{__python} test.py


%install
%{__rm} -rf ${RPM_BUILD_ROOT}
%{__python} setup.py install -O1 --skip-build --root ${RPM_BUILD_ROOT}
%{__mkdir} -p -m 0750 ${RPM_BUILD_ROOT}/etc/%{libname}/totp
%{__mkdir} -p -m 0700 ${RPM_BUILD_ROOT}/var/lib/%{libname}
%{__mkdir} -p ${RPM_BUILD_ROOT}/var/www/%{libname}
%{__cp} totp.cgi ${RPM_BUILD_ROOT}/var/www/%{libname}/
%{__mkdir} -p ${RPM_BUILD_ROOT}/etc/httpd/conf.d
%{__cp} contrib/vhost-totp-cgi.conf ${RPM_BUILD_ROOT}/etc/httpd/conf.d/totp-cgi.conf

%pre
# Add the "toptcgi" user
/usr/sbin/useradd -c "Toptcgi" \
	-M -s /sbin/nologin -d /var/lib/%{libname} %{libname} 2> /dev/null || :

%post
# install the selinux policy
cd %{_docdir}/%{name}-%{version}/selinux
./totpcgi.sh

%preun
# remove the selinux policy
/usr/sbin/semodule -r totpcgi
# Cleanup from our original install of the policy
# I would use a ghost tag but it's annoying sometimes
%{__rm} -rf %{_docdir}/%{name}-%{version}/selinux/tmp
%{__rm} -f %{_docdir}/%{name}-%{version}/selinux/totpcgi.pp

%files
%doc README.rst COPYING INSTALL.rst
%doc selinux contrib
%doc totp.fcgi totpcgi.psql
%{python_sitelib}/*
%attr(0750, root, %{libname}) /etc/%{libname}
%attr(-, %{libname}, %{libname}) /var/lib/%{libname}
%attr(0550, %{libname}, %{libname}) /var/www/%{libname}
%attr(0664, %{libname}, %{libname}) /var/www/%{libname}/totp.cgi
%config %attr(0644, -, -) /etc/httpd/conf.d/totp-cgi.conf

%changelog
* Wed Mar 21 2012 Andrew Grimberg <agrimberg@linuxfoundation.org> - 0.2.0-1
- Initial spec file creation and packaging
